eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: service-zuul
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      
zuul:
  routes:
    service-a:
      path: /video/**
      sensitiveHeaders: 
      service-id: service-video
  sensitiveHeaders:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
          ribbon:
            ReadTimeout: 60000
            ConnectTimeout: 60000
            
ribbon:
    ReadTimeout: 60000
    SocketTimeout: 60000
    ConnectTimeout: 60000
    
    
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
    