eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: service-zuul
      
zuul:
  routes:
    service-a:
      path: /video/**
      sensitiveHeaders: 
      service-id: service-video
  sensitiveHeaders:
  host:
    socket-timeout-millis: 100000
    connect-timeout-millis: 100000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
          ribbon:
            ReadTimeout: 100000
            ConnectTimeout: 100000
            
ribbon:
    ReadTimeout: 100000
    SocketTimeout: 100000
    ConnectTimeout: 100000
    
    
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: basic
    