eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: service-zuul
zuul:
  routes:
    service-a:
      path: /video/**
      sensitiveHeaders: 
      service-id: service-video
  sensitiveHeaders:
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    