eureka-server:
  image:  dw/eureka
  hostname: eureka-server
  ports:
    - "8761:8761"
 
service-zuul:
  image:  dw/zuul
  ports:
    - "8081:8081"
  links:
    - "eureka-server"
    
service-jwt:
  image:  dw/jwt
  ports:
    - "8763:8763"
  links:
    - "eureka-server"
    - "service-zuul"
    
service-elasticsearch:
  image:  dw/elasticsearch
  ports:
    - "8764:8764"
  links:
    - "eureka-server"
    - "service-zuul"
    
service-video:
  image:  dw/videos
  ports:
    - "8762:8762"
  links:
    - "eureka-server"
    - "service-zuul"
    
