eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: service-zuul
      
zuul:
  routes:
    service-video:
      path: /video/**
      sensitiveHeaders: 
      service-id: service-video
  sensitiveHeaders:
  host:
    socket-timeout-millis: 400000
    connect-timeout-millis: 400000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 400000
            
ribbon:
    ReadTimeout: 1600000
    SocketTimeout: 1600000
    ConnectTimeout: 1600000
    
#单独为video文件上传设置熔断时间

    
    