server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false    #检索服务
    serviceUrl:
      defaultZone: http://10.0.0.92:${server.port}/eureka/
  server:
    enable-self-preservation: false  #关闭自我保护机制
    eviction-interval-timer-in-ms: 10000 #每隔10s扫描服务列表，移除失效服务
