eureka:
  instance:
    hostname: service-db
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-db
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    #url: jdbc:mysql://172.18.62.91:3306/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    initialSize: 5
    minIdle: 5
    maxActive: 20   
    maxWait: 60000  
    filters: stat
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true
    
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ribbon:
  eureka:
    enabled: true
  
  
  
  