eureka:
  instance:
    hostname: service-jwt
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-jwt


  
ribbon:
  eureka:
    enabled: true
    