eureka:
  instance:
    hostname: service-jwt
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8763
  
spring:
  profiles: docker
  application:
    name: service-jwt
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://172.18.62.91:3306/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    initialSize: 5
    minIdle: 5
    maxActive: 20   
    maxWait: 60000  
    filters: stat
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true
    
mybatis:
  type-aliases-package: com.itcast.dw.model
  mapper-locations: classpath:mapper/*.xml
  mappers: com.itcast.dw.baseDao.BaseMapper
  not-empty: false

# 分页配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: false
  reasonable: true
  page-size-zero : true
  
ribbon:
  eureka:
    enabled: true
  
  
  
  