eureka:
  instance:
    hostname: service-video
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-video
  http:
    multipart:
      enabled: true
      max-file-size: 2048Mb      # Max file size，默认1M
      max-request-size: 2048Mb   # Max request size，默认10M
      
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 600000
        loggerLevel: basic
        
        