eureka:
  instance:
    hostname: video
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://47.107.95.112:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: video
  http:
    multipart:
      enabled: true
      max-file-size: 2048Mb      # Max file size，默认1M
      max-request-size: 2048Mb   # Max request size，默认10M
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    username: root
    password: Aa123456
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    initialSize: 5
    minIdle: 5
    maxActive: 20   
    maxWait: 60000  
    filters: stat
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true
    
mybatis:
  type-aliases-package: com.itcast.dw.model
  mapper-locations: classpath:mapper/*.xml
  mappers: com.itcast.dw.baseDao.BaseMapper
  not-empty: false
  
# 分页配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: false
  reasonable: true
  page-size-zero : true
      
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 600000
        loggerLevel: basic

#video path

video:
  path:  E:/video/
        
        