eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.62.91:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-video
  http:
    multipart:
      enabled: true
      max-file-size: 2048Mb      # Max file size，默认1M
      max-request-size: 2048Mb   # Max request size，默认10M
      
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 60000
        loggerLevel: basic
        
        