eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-video
    
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic
        
        