spring:
  profiles:
    active: dev
   #Redis配置
  #redis:
    #database: 0 # Redis数据库索引（默认为0）
   # host: localhost  #Redis服务器地址
    #port: 6379 # Redis服务器连接端口
   # password: # Redis服务器连接密码（默认为空）
   # pool:
     # max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
     # max-idle: 10 # 连接池中的最大空闲连接
     # max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
     # min-idle: 5 # 连接池中的最小空闲连接
      #timeout: 1000 # 连接超时时间（毫秒）
  cloud:
    refresh:
      refreshable: none
  bus:
    trace:
      enabled: true    #开启消息跟踪
    enabled: true
#
#ribbon:
#  eureka:
#    enabled: true

project:
  config:
    jwt-securt: Fl9UOH7Q3&ut4Qtr-szbdc
    jwt-ttl: 604800
    token-ttl: 1800
    kaptcha-token-ttl: 120
    login-failed-number-ttl: 86400
    login-failed-number: 5

logging:
  config: classpath:logback.xml
  path: ./logs/videos
  #level:
    #org.springframework.web: DEBUG



