eureka:
  instance:
    hostname: service-elastic
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  #profiles: docker
  application:
    name: service-elastic
  cloud:
    refresh:
      refreshable: none
  data:
    elasticsearch:
      clusterNodes: 47.107.95.112:9300
      clusterName: my-application
     
    
ribbon:
  eureka:
    enabled: true        
        