eureka:
  instance:
    hostname: service-elastic
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8764
spring:
  profiles: docker
  application:
    name: service-elastic
    
ribbon:
  eureka:
    enabled: true        
        