eureka:
  instance:
    hostname: service-redis
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
  
spring:
  application:
    name: service-redis
  #Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 5 # 连接池中的最小空闲连接
      timeout: 1000 # 连接超时时间（毫秒）

ribbon:
  eureka:
    enabled: true
  
  
  
  